### ISSUE TITLE
As an admin I want to be able to create reports of the inventory so that I can view inventory statistics and identify trends.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/ReportProvider#10]
#### Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [ ] The admin can see an overview of the inventory.
- [ ] A pie chart over inventory categories.
- [ ] A line chart for inventory over time.
- [ ] Filtering and sorting for product categories, dates.
- [ ] There needs to be a generate report button to create a downloadable document.

# Tasks:
- [ ] KYH-Net23/ReportProvider#11
- [ ] KYH-Net23/ReportProvider#12
- [ ] KYH-Net23/Rika#89

# Test Cases:
### **Steps:**
- [ ] Admin chooses file format pdf.
- [ ] Admin presses the “Download report” button.
### **Expected Results: **
- [ ] A pdf inventory report file is generated and downloaded.

### **Steps:**
- [ ] Admin chooses file format csv
- [ ] Admin presses the “Download report” button.

### **Expected Results:**
- [ ] A csv inventory report file is generated and downloaded.

# Activity Diagram:

![Image](https://github.com/user-attachments/assets/5e503e3a-b86d-4440-aab5-dbd408f15370)
